### PR TITLE
Pr 83

### PR DESCRIPTION
**Pull request by adibender**

### CODE REVIEW

**Comment by fabian-s** [comment]
you like this, then? fine to merge by me,  obvsly, if travis agrees as well

**Comment by adibender** [comment]
works very well, but one more thing: 

- for non TDC data, we have `time[status == 1]` as default and all censored observations censored at `max(time[status == 1])`
- for TDC case we have `union(time[status == 1], tz), and max(event time) can be < max(tz) 

should we handle this or leave to user?

**Comment by fabian-s** [comment]
I think that:

* event times are primary and the most important
* we should warn users in case we see max(time) > max(tz) (extrapolation of TDCs?), I don't see any issue  with the case you mention (max(time) < max(tz))

Do we currently censor at `time > max(tz)`? Should we?

Also:  should concurrent effects with lag enforce truncation of the data to start modeling the hazard at `lag` instead of `0`?

**Comment by adibender** [comment]
> we should warn users in case we see max(time) > max(tz) (extrapolation of TDCs?)
I don't see much difference between assuming constant TDC value observed at 0 for all intervals between (0, 100) and constant TDC value observed at max(time) - 100 for all intervals in (max(time) -100, max(time))

> I don't see any issue with the case you mention (max(time) < max(tz))
not an issue per se, but not consistent. For normal data, default is that last \kappa_J = event time, for TDC could be \kappa_J = censoring time (at max(tz)). 
Also, don't quite understand how that happens. When subject i has censoring time at t_i = 5000 and last observation of z at tz = 5100, shouldn't t_i = 5100 ?

> Do we currently censor at time > max(tz)?
yes, unless max(tz) < max(event time)

> Should we?
probably not. I think either censor at max(event time) or max(max(event time), max(censoring time))

**Pull request merged**
